---
author: "Andrew Nalundasan"
purpose: "OMSBA 5280, Seattle University"
title: "Reading Questions 10"
date: "August 27, 2021"
output: 
  word_document:
    reference_docx: W2-2-2-2_word_memo_template.docx
---


1. If the right to privacy requires we have an “expectation of privacy”, how can we argue that surveillance of our faces conducted while in public is a violation?

While I am out in public going about my private business, I do not want to have to think about if I am being watched or not. Knowing myself, having the feeling that I am being watched either by a person or by a machine would be a constant anxiety that I would have to live with. The mental health implications of this possibility would be drastic for the general population. S. 847 states that "the noted exceptions would not permit businesses to conduct the mass scanning of faces in spaces where persons do not have a reasonable expectation that facial recognition technology is being used on them". Private citizens should have the right to expect privacy and be informed when their faces would bu subject to surveillance. Perhaps the notification of the use of facial recognition technology when stepping into a brick and mortar storefront could be similar to entering a website on the internet and being notified about the use of cookies. People would become familiar with these notifications at the store's front door just as they are familiar with the classic neon 'closed' and 'open' signs. If these signs are not at the front door of the establishment, or elsewhere within the store, I believe a private citizen should have the expectation that their face data is not being monitored, scanned, or stored for later use. If surveillance takes place without consent of the individual, it would be considered an invasion of privacy. Face data is biometric data, meaning it is irreplaceable and poses a severe threat to privacy if the data is compromised. Unlike non-biometric data, where a credit card number could be replaced or a password could be reset. 

2. Do you believe the concerns regarding bias and privacy warrant state and federal legislation? Please explain.

I do believe that facial recognition technology (FR tech) warrants state and federal legislation. If no legislation is passed to grant protections to private citizens from being surveyed, government and business would be able to constantly maintain surveillance on target areas, groups, customers, or consumers, with no limit to what they could do with the data that they collect. This compilation of data would continue to "feed the beast" of big data where inherent bias will continue to compound on itself. Government has no place directing private citizens on what they can and cannot do. Sadly, we have learned about many examples of life altering decisions being made by FR tech that are acted upon by law enforcement. Yes, there are certainly success stories as well, but I believe that we can still have the successes of FR tech with the implementation of legal regulation so that the civil liberties of all people are protected. With proper state and federal legislation, law enforcement would get the support that they need from FR tech without wrongfully making life altering decisions on innocent people. The use of FR tech by law enforcement must be regulated for the protection of the general public. Equipping law enforcement with FR tech without proper state and federal legislation essentially takes America one step closer to being a surveillance state. This is why I support the development of state and federal legislation around FR tech. 

3. Do you think existing legislation (e.g., in Illinois and California) goes far enough to protect civil liberties? Please explain and include in your answer your thoughts about "consent" and private right causes of action.

CCPA - people have the right to request disclosure of the information being tracked on them - categories and specific pieces of personal information that it collects about the consumer

Biometric Information Privacy Act - city of Chicago is pilot site for biometric data. Written policy for collection, discolsure, and destruction of the info. Since face data is biometric data, it should be treated with utmost care by the individual. 

I believe that existing legislation in Illinois (Biometric Information Privacy Act) and California (California Consumer Privacy Act) just barely scratch the surface of protecting civil liberty of privacy. Based on my understanding of these regulations, it seems that the protections provided would only benefit individuals educated enough to understand the implications of the data collection. I do not believe the average American realizes the implications of big data having their information. So these regulations provide rights to request information about the categories and specific pieces of personal information that is being collected, but who would actually make those requests and what would they actually do with the information? The only actionable thing I can think of would be the individual making the choice to not do business with a company that tracks too much of their information. But again, I only see this happening for people that understand the nuances of big data, while the vast majority will continue to give up their information for free.  

I believe private citizens should be provided with the opportunity to opt-out of technology that they do not wish to be subject to. It does make sense to go through body scans, etc. when going through airport security, but I believe there is a fine line between security/safety and being monitored without consent. In our every day lives as we run errands like grocery shopping or taking the kids to play in a public park, I do not believe that our faces should be monitored. High risk places with potential security threats like a sporting event might warrant the monitoring, but it does not make sense to me for this level of monitoring to be taking place on a daily basis just to help companies make a profit.  

4. In that absence of legal regulation, do you think businesses using this technology will self-regulate and if so how?

I have to say that I am very skeptical about businesses using FR tech to self-regulate. The farthest that I see businesses going to self-regulate would be if they took the "Compliance Approach" as discussed in our Week 8 materials. I could see businesses doing the bare minimum to self-regulate the data that they compile using FR tech, just to check off a box on their scorecards to say they are in compliance. I do not think it makes business sense to self-regulate if there are no legal regulations in place. Businesses would benefit greatly by collecting as much data as they can before legal regulations are passed. The only reason a business would maintain the "Compliance Approach" would be to write about it in some report that goes out to customers and stakeholders. Businesses will continue to collect as much data as they can about their customers and their own employees until they become at risk of legal implications. Once legal regulations are put in place, I still believe that businesses will think of ways around the law, or loopholes, to continue collecting information on their customers and employees. There is too much profit to be made to not collect the information. 

